name: python-api-demo-cicd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: codebuild-python-lambda-api-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
    - uses: actions/checkout@v4
    - uses: aws-actions/setup-sam@v2
      with:
        use-installer: true
        token: ${{ secrets.GITHUB_TOKEN }}
    # - name: Set up Python 3.10.14
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: "3.10.14"
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install flake8 pytest
    #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - name: Build SAM Application
    #   uses: actions/checkout@v4
    - run: sam build --use-container
    - run: csam deploy --no-confirm-changeset --no-fail-on-empty-changeset

